KS 20 - 5: Completed task number 5 for lesson 20
RomkaGra4/KotlinSprint pull request #100
Opened 2023-11-24 19:38 UTC by RomkaGra4

2023-11-25 15:08 UTC, ievetrov requested changes

2023-11-25 15:08 UTC, ievetrov commented on src/main/kotlin/lesson_20/lesson_20_task_5.kt
> +    fun setModifier(): String {
Предлагаю немного изменить подход. пусть метод принимает модификатор (лямбду) и присваивает его поля класса
```
fun setModifier(modifier: (String) -> String) {
    this.modifier = modifier
}
```

Для этого модификатор надо объявить в классе, который будет просто принимать и взвращать одну и ту же строку (реализация по умолчанию)
`private var modifier: (String) -> String = { it }`

2023-11-25 15:08 UTC, ievetrov commented on src/main/kotlin/lesson_20/lesson_20_task_5.kt
> +fun main() {
И в мейне нам уже потребуется вызывать setModifier и поставлять в него некую функцию модификатор. Например, reversed() по отношению к строке (которая входит в лямбду)

2023-11-29 21:29 UTC, RomkaGra4 commented
И так. Посмотрим, что я сделал :)))
Дай пожалуйста обратную связь по моей корректировке

2023-11-30 16:54 UTC, ievetrov requested changes
хорошо)

2023-11-30 16:54 UTC, ievetrov commented on src/main/kotlin/lesson_20/lesson_20_task_5.kt
> +    phrases.say()
отлично, после этого вызывай setModifier в который поставляй функцию разворота переданной строки, а потом попробуй опять вызвать say() )

2023-12-05 10:10 UTC, ievetrov requested changes
вот тут написал в чем смысл предыдущих действий и как это запустить)

<img width="879" alt="Снимок экрана 2023-12-05 в 14 09 44" src="https://github.com/RomkaGra4/KotlinSprint/assets/34489023/a420e756-6439-4929-890b-c44bb98b023b">

2023-12-05 22:34 UTC, RomkaGra4 commented
Объясни, а зачем нам надо было reversed() указывать? Если я правильно понял - в ТЗ не было такой задачи... Чет туплю в этом моменте страшно))

2023-12-06 17:07 UTC, ievetrov commented
> Объясни, а зачем нам надо было reversed() указывать? Если я правильно понял - в ТЗ не было такой задачи... Чет туплю в этом моменте страшно))

так вроде там написано про инверсию слов) можем дообсудить если что пиши в лс)

> Робот произносит одну из случайных 5 фраз (придумай фразы самостоятельно). Реализуй модификатор, инвертирующий слова робота.

2023-12-06 17:08 UTC, ievetrov approved these changes

2024-04-25 19:53 UTC, merged