KS 21 - 2: Completed task number 2 for lesson 21
RomkaGra4/KotlinSprint pull request #102
Opened 2023-12-05 22:30 UTC by RomkaGra4

2023-12-06 17:18 UTC, ievetrovdev requested changes

2023-12-06 17:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson_21_task_2.kt
> +fun File.evenNumbersSum() {
нужна функция для списка инт чисел, а не файла

2023-12-06 17:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson_21_task_2.kt
> +    val numbers = listOf(5, 3, 2, 4, 6)
здесь не нужно создавать список, мы вызываем эту функцию к списку снаружи
`list.evenNumbersSum()`

2023-12-06 17:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson_21_task_2.kt
> +    val file = File("")
файл здесь не нужен)

2023-12-17 18:07 UTC, RomkaGra4 commented
Слушай, если все верно - то я примерно понял суть темы :)) Через практику)

2023-12-17 23:19 UTC, ievetrovdev approved these changes

2023-12-18 14:37 UTC, merged