KS 21 - 3: Completed task number 3 for lesson 21
RomkaGra4/KotlinSprint pull request #103
Opened 2023-12-18 18:59 UTC by RomkaGra4

2023-12-19 02:20 UTC, ievetrovdev requested changes

2023-12-19 02:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson_21_task_3.kt
> +    print(this.currentHealth == this.maxHealth)
все ок, только давай здесь возвращать результат сравнения (булеан)

2023-12-25 02:05 UTC, ievetrovdev requested changes

2023-12-25 02:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson_21_task_3.kt
> +    print(result)
если эта функция возвращает результат, то принта здесь не должно быть. чтобы мы могли получить ответ из функции нам нужно сделать таким образом:
`fun Player.isHealthy() : Boolean = this.currentHealth == this.maxHealth`

2023-12-25 17:59 UTC, RomkaGra4 commented on src/main/kotlin/lesson_21/lesson_21_task_3.kt
> +    print(result)
Ок, понял. Исправляем)

2023-12-26 01:28 UTC, ievetrovdev approved these changes

2024-05-17 16:00 UTC, merged