KS-4-5: completed the fifth task of the FOURTH lesson
RomkaGra4/KotlinSprint pull request #20
Opened 2023-03-31 23:45 UTC by RomkaGra4

2023-04-01 18:12 UTC, ievetrov requested changes

2023-04-01 18:12 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val shipDamage: Boolean = readLine()!!.toBoolean()
ридлайн возвращает нулябельный тип, да. но оператор !! использовать не рекомендуется. он опасен тем, что утверждает "это не null" и когда в него попадает null - программа падает. посмотри на канале урок про нулябельность, там будет подробнее

тут рекомендую использовать readln(), потому что под капотом код преобразуется в ненулабельный тип. и операторы безопасного вызова и "это не нуль" тут без надобности

2023-04-01 18:12 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val crewSize = readln()!!.toInt()
тут все так. но !! не нужны, причина выше

2023-04-01 18:12 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val provisions = readln()!!.toInt()
и тут

2023-04-01 18:12 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +                (((crewSize == 70) && favorableWeatherToday == FAVORABLE_WEATHER_CONDITIONS) && provisions > 50)
работает, но все эти этажи можно подсократить. забегая вперед покажу оптимизацию с проверкой вхождения в диапазоне 
```
val result = (favorableWeatherToday == FAVORABLE_WEATHER_CONDITIONS) && (provisions > 50) && (
            (shipDamage != NO_DAMAGE) && (crewSize in 56..69) || crewSize == 70)
```

2023-04-01 18:12 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +                (((crewSize == 70) && favorableWeatherToday == FAVORABLE_WEATHER_CONDITIONS) && provisions > 50)
но осталась другая проблема
значения в этом коде являются [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)
не лучшая практика. добавь, пожалуйста, переменные)

2023-04-02 17:20 UTC, RomkaGra4 commented
Внес корректировки. И "завис" на добавлении переменных. А точнее использование переменных в диапазоне.
Т.к. у нас в первом случае от 55 до 70 НЕ включительно, я посчитал нужным не создавать дополнительные(левые) переменные а просто прибавил и вычел по единице. Однако долго думал над тем - применяется ли такое в практике... Сомнений становится больше когда вижу подчеркивание со стороны Идееи именно в этом моменте "(minCrew + 1)..(recommendedCrew - 1)". 

Подскажи, корректен ли такой вариант? Или нужно еще поломать голову над тем - как выходить из таких ситуаций?) 
P.S. Я пошел на мой взгляд по пути наименьшего сопротивления, но не понимаю на сколько это корректно :))

2023-04-03 06:26 UTC, ievetrov requested changes
не совсем корректен, диапазоны позволяют включать и не включать значения. например с помощью ключевого слова until
 кроме того ты можешь видеть что именно подчеркивает Идея (даже предлагает исправления)

2023-04-05 06:24 UTC, ievetrov requested changes

2023-04-05 06:24 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val result = (favorableWeatherToday == FAVORABLE_WEATHER_CONDITIONS) && (provisions > minProvision) && ((shipDamage != NO_DAMAGE) && (crewSize in minCrew until recommendedCrew) || (crewSize == re
Очень длинная строка получилась. В крупных и средних проектах есть системы для автоматизированной проверки кода, например: [Detekt](https://detekt.dev/docs/rules/formatting/#maximumlinelength), который не пропустит такой код. Давай добавим переносов

2023-04-06 13:35 UTC, ievetrov approved these changes
отлично!

2023-04-06 16:22 UTC, merged