KS-5-2: completed the second task of the fifth lesson
RomkaGra4/KotlinSprint pull request #22
Opened 2023-04-01 00:33 UTC by RomkaGra4

2023-04-01 18:14 UTC, ievetrov requested changes

2023-04-01 18:14 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_2.kt
> +    val age = readLine()!!.toInt()
!!

2023-04-01 18:14 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_2.kt
> +    if ((2023 - age) >= 18)
а зачем объявлял константу?)

2023-04-02 17:27 UTC, RomkaGra4 commented on src/main/kotlin/lesson_5/lesson_5_task_2.kt
> +    if ((2023 - age) >= 18)
ой, точно :)

2023-04-03 18:34 UTC, ievetrov approved these changes

2023-04-04 19:13 UTC, merged