KS-1-3: completed the third task of the first lesson
RomkaGra4/KotlinSprint pull request #3
Opened 2023-03-24 21:18 UTC by RomkaGra4

Вопрос: в задании "Выведи год, час и минуту взлета по одной переменной на каждую строку" нужно было чтобы вывелось именно час "09" и минута "07" в каждой строке? Или достаточно было указать цифры без нуля впереди (т.е. как в моем решении)?

2023-03-25 07:45 UTC, ievetrov requested changes
верно заметил) да, мы всегда придерживаемся требований ТЗ (если они прописаны явно). поэтому тут нужно вывод сделать по примеру)

2023-03-28 22:05 UTC, RomkaGra4 commented
> верно заметил) да, мы всегда придерживаемся требований ТЗ (если они прописаны явно). поэтому тут нужно вывод сделать по примеру)

Внес поправки. Как я понял - тут все очень просто: нужно поставить другой тип переменной, верно ?)

2023-03-29 09:46 UTC, ievetrov commented
> > верно заметил) да, мы всегда придерживаемся требований ТЗ (если они прописаны явно). поэтому тут нужно вывод сделать по примеру)
> 
> Внес поправки. Как я понял - тут все очень просто: нужно поставить другой тип переменной, верно ?)

да) ну и обратить внимание, что целое число с нулем в начале не работает

2023-03-29 09:47 UTC, ievetrov approved these changes
все ок!

2023-03-29 14:35 UTC, merged