KS-10-3: completed the third task of the TENth lesson
RomkaGra4/KotlinSprint pull request #50
Opened 2023-04-08 11:04 UTC by RomkaGra4

2023-04-09 10:30 UTC, ievetrov requested changes

2023-04-09 10:30 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task3.kt
> +fun passwordGeneration(passwordLength: Int): String {
вопрос по неймингу. 
тут также корректнее будет звучать generatePassword или getGeneratedPassword
вообще чем подробнее описано действие, тем лучше

2023-04-13 09:58 UTC, ievetrov requested changes
рекомендую использовать шорткат для автоматического форматирования перед коммитом cntrl + alt + L

2023-04-13 09:58 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task3.kt
> +    println(generatePassword (passwordLength))
между названием функции и скобками с параметрами не должно быть пробелов

2023-04-13 09:58 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task3.kt
> +fun generatePassword (passwordLength: Int): String {
и тут

2023-04-13 15:45 UTC, RomkaGra4 commented on src/main/kotlin/lesson_10/lesson_10_task3.kt
> +fun generatePassword (passwordLength: Int): String {
О, круто! Спасибо!) Сразу аккуратнее стало)

2023-04-14 09:44 UTC, ievetrov approved these changes

2023-04-14 12:37 UTC, merged