Kotlin Sprint: Lesson 11, task 2
RomkaGra4/KotlinSprint pull request #52
Opened 2023-04-14 20:15 UTC by RomkaGra4

2023-04-14 20:27 UTC, ievetrov requested changes

2023-04-14 20:27 UTC, ievetrov commented on src/main/kotlin/lesson_1_10/lesson_3/lesson_3_task_5.kt
> +package lesson_1_10.lesson_3
вот, а что произошло? ))

2023-04-14 20:27 UTC, ievetrov commented on src/main/kotlin/lesson_11_task_2/UserData.kt
> +class UserData(
а давай класс UserData положим рядом с функцией main()

2023-04-14 20:27 UTC, ievetrov commented on src/main/kotlin/lesson_11_task_2/UserData.kt
> +        println(""""Данные пользователья:
опечатка

2023-04-14 20:41 UTC, RomkaGra4 commented on src/main/kotlin/lesson_1_10/lesson_3/lesson_3_task_5.kt
> +package lesson_1_10.lesson_3
Если честно - я сам не понял что произошло)) На видео объединение 10 пакетов в один казалось таким простым. А у меня все "пошло-поехало"...

2023-04-14 20:59 UTC, RomkaGra4 commented on src/main/kotlin/lesson_11_task_2/UserData.kt
> +        println(""""Данные пользователья:
исправил!

2023-04-15 20:17 UTC, ievetrov approved these changes

2023-04-15 20:17 UTC, ievetrov commented on src/main/kotlin/lesson_1_10/lesson_3/lesson_3_task_5.kt
> +package lesson_1_10.lesson_3
ну такие вещи в ветке с задачей не делаются, либо в отдельной, либо в рамках нашей движухи можно в мастер сразу комитить

2023-04-16 06:05 UTC, merged