Kotlin Sprint: Lesson 11, task 4
RomkaGra4/KotlinSprint pull request #54
Opened 2023-04-15 09:39 UTC by RomkaGra4

2023-04-15 22:14 UTC, ievetrov requested changes
и не понимаю, почему в каждом ПР изменения во всех задачках.. ты в каждой рабочей ветке переименовывал каждый раз все пакеты?)

2023-04-15 22:14 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_4.kt
> +){}
пустые скобки

2023-04-15 22:14 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_4.kt
> +    val myPeople: FavoriteContacts,
тут лучше FavoriteContacts обозвать в единственном числе (все таки класс надо воспринимать как чертеж для единственного экземпляра)
и сделать свойство с типом "список объектив типа FavoriteContact"

2023-04-16 06:20 UTC, RomkaGra4 commented
> и не понимаю, почему в каждом ПР изменения во всех задачках.. ты в каждой рабочей ветке переименовывал каждый раз все пакеты?)

Нет!) Я просто хотел объединить с 1 по 10 уроки в 1 пакет как это было сделано в видео. Мне показалось это удобным и красивым. Но как только я объединил - все пошло по одному месту. Потом я не понял - толи я в мастер ветке все это сделал, толи в отдельной ветке, но у меня каким-то образом все смешалось. В общем я понимаю что на 11 уроке "посыпался конкретно"... Не знаю как поступить, чтобы все отмотать назад и спокойно продолжить выполнение задач))

2023-04-18 06:23 UTC, ievetrov commented
> > и не понимаю, почему в каждом ПР изменения во всех задачках.. ты в каждой рабочей ветке переименовывал каждый раз все пакеты?)
> 
> Нет!) Я просто хотел объединить с 1 по 10 уроки в 1 пакет как это было сделано в видео. Мне показалось это удобным и красивым. Но как только я объединил - все пошло по одному месту. Потом я не понял - толи я в мастер ветке все это сделал, толи в отдельной ветке, но у меня каким-то образом все смешалось. В общем я понимаю что на 11 уроке "посыпался конкретно"... Не знаю как поступить, чтобы все отмотать назад и спокойно продолжить выполнение задач))

ок) ну тут только все домержить уже и все новые ветки создавать правильно
когда делаешь коммит - смотри что отмечено галками. чтобы не относящиеся к задаче файлы не попали в стейдж и в коммит

2023-04-18 06:23 UTC, ievetrov approved these changes

2023-04-18 07:01 UTC, merged