KS 13 - 3: Completed task number 3 for lesson 13
RomkaGra4/KotlinSprint pull request #61
Opened 2023-04-20 17:35 UTC by RomkaGra4

2023-04-21 14:44 UTC, ievetrov requested changes

2023-04-21 14:44 UTC, ievetrov commented on src/main/kotlin/lesson_13/lesson_13_task_3.kt
> +    val contact1 = TelephoneBook(name = "Роман", company = "FM Logistic")
> инициализируя их с разнообразными данными (в том числе и null)

надо также учитывать поведение, что при создании объекта придет null. такая ситуация более вероятна

2023-04-22 10:38 UTC, ievetrov requested changes

2023-04-22 10:38 UTC, ievetrov commented on src/main/kotlin/lesson_13/lesson_13_task_3.kt
> +
лишняя пустая строка

2023-04-22 10:38 UTC, ievetrov commented on src/main/kotlin/lesson_13/lesson_13_task_3.kt
> +class TelephoneBook(
тот же короткий коммент про нейминг

2023-04-26 12:24 UTC, ievetrov requested changes

2023-04-26 12:24 UTC, ievetrov commented on src/main/kotlin/lesson_13/lesson_13_task_3.kt
> +    for (i in contactsList) {
этот цикл тут не обязателен и даже может оказаться вреден.
Ведь по факту ты заменяешь null значение на "[не указано]", твой список после выполнения этого цикла будет другим.

А если предположим, я попрошу тебя отфильтровать все контакты, у которых не указано имя? `contactsList.filter { it.name != null  } ` не сработает.

Если ты сделаешь `contactsList.filter { it.name != "[не указано]"  } `, это сработает, но тогда код станет плохо поддерживаемым, если например заказчик попросит добавить английский язык, и в одном случае это будет [not set] в другом [не указано].

Короче, давай когда println делаешь, тогда и подставлять `?:  "[не указано]"`

2023-04-28 18:39 UTC, RomkaGra4 commented on src/main/kotlin/lesson_13/lesson_13_task_3.kt
> +    for (i in contactsList) {
Окей, понял! Спасибо что "разжевал"))) Так стало понятнее и код более компактным))

2023-04-29 14:16 UTC, ievetrov approved these changes
отлично!

2023-05-02 17:30 UTC, merged