KS-2-2: completed the third task of the SECOND lesson
RomkaGra4/KotlinSprint pull request #8
Opened 2023-03-28 20:35 UTC by RomkaGra4

2023-03-29 09:27 UTC, ievetrov requested changes
пропущены пункты по условию "Создай целочисленные переменные и проинициализируй их этими данными". по ТЗ надо делать сначала инициализацию, потом вычисления

2023-03-29 09:27 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task_3.kt
> +
остались лишние пустые строки

2023-03-29 14:58 UTC, RomkaGra4 commented on src/main/kotlin/lesson_2/lesson_2_task_3.kt
> +
Сделал. Прошу проверить!)

2023-03-30 08:23 UTC, ievetrov approved these changes
все чисто)

2023-03-30 14:22 UTC, merged