KS 17 - 2:  Completed task number 2 for lesson 17
RomkaGra4/KotlinSprint pull request #80
Opened 2023-07-08 14:23 UTC by RomkaGra4

2023-07-08 15:54 UTC, ievetrov requested changes

2023-07-08 15:54 UTC, ievetrov commented on src/main/kotlin/lesson_17/lesson_17_task_2.kt
> +            if (value != "Титаник")
- "Титаник" тут это и есть field. field олицетворяет значение , которое сохранено в поле
- однако тут field = value ты уже присвоил новое значение полю, что не соответствует условию тз. лучше вообще при попытке вызова сеттера сразу возвращать принт с предупреждением. (сразу через равно)

2023-07-08 17:49 UTC, RomkaGra4 commented on src/main/kotlin/lesson_17/lesson_17_task_2.kt
> +            if (value != "Титаник")
Окей. Просто когда я меняю название, у меня выходит предупреждение. Но вместе с тем и меняется название. А в тз указано что "менять нельзя". Т.е. я думал в буквальном смысле :)

2023-07-08 19:28 UTC, ievetrov commented on src/main/kotlin/lesson_17/lesson_17_task_2.kt
> +            if (value != "Титаник")
так а фишка переопределения сеттера в том, что он и не поменяет название)

а ты его и меняешь, получается, вот тут `field = value`

то есть что происходит:
- в коде мейна пытаешься задать новое имя
- под капотом обычно вызывается сеттер со строкой `field = value` тем самым присваивая твое новое значение из вэлью полю переменной филд
- но так как мы переопределяем сеттер, мы это поле убираем. чтобы вообще нельзя было ничего присвоить, а только выводим оповещение
```
    var name: String = _name
        set(value) {
            println("Имя корабля изменить нельзя")
        }
```

2023-07-08 19:29 UTC, ievetrov requested changes
оставил коммент)

2023-07-10 17:24 UTC, RomkaGra4 commented on src/main/kotlin/lesson_17/lesson_17_task_2.kt
> +            if (value != "Титаник")
фантастика)) Все намного проще чем я думал)

2023-07-10 21:45 UTC, ievetrov approved these changes
огонь)

2023-07-11 17:25 UTC, merged