KS 18 - 3:  Completed task number 3 for lesson 18
RomkaGra4/KotlinSprint pull request #86
Opened 2023-07-18 20:10 UTC by RomkaGra4

2023-07-19 10:00 UTC, ievetrov requested changes

2023-07-19 10:00 UTC, ievetrov commented on src/main/kotlin/lesson_18/lesson_18_task_3.kt
> +open class Tamagotchi {
про абстракцию писал ранее, давай тут тоже сделаем

2023-07-19 10:00 UTC, ievetrov commented on src/main/kotlin/lesson_18/lesson_18_task_3.kt
> +    override fun sleep(): String {
можно в более короткой форме писать без return все функции

2023-07-19 10:00 UTC, ievetrov commented on src/main/kotlin/lesson_18/lesson_18_task_3.kt
> +    override fun sleep(): String {
и согласно ТЗ нужно переопределить методы игры

2023-07-20 18:44 UTC, RomkaGra4 commented on src/main/kotlin/lesson_18/lesson_18_task_3.kt
> +    override fun sleep(): String {
Готово. Посмотри, я в нужном направлении?)

2023-07-20 21:01 UTC, ievetrov requested changes

2023-07-20 21:01 UTC, ievetrov commented on src/main/kotlin/lesson_18/lesson_18_task_3.kt
> +
совершенно верно!
тут предлагаю только поубирать пропуски между функциями для большего единообразия

2023-07-20 21:01 UTC, ievetrov commented on src/main/kotlin/lesson_18/lesson_18_task_3.kt
> +    open fun eat() = "$name - ест $food"
В условии еще есть информация о том, что все звери могут играть. И спасть тоже. А значит это признак того, что для этих действий можно сделать реализацию по умолчанию в абстрактном классе и не переопределять их.

С едой иначе - так как у каждого своя. Поэтому лучше тут сделать абстрактные функции и реализовывать их в дочерних классах.

2023-07-21 17:39 UTC, ievetrov requested changes

2023-07-21 17:39 UTC, ievetrov commented on src/main/kotlin/lesson_18/lesson_18_task_3.kt
> +    open fun eat() = ""
все отлично, но как я говорил ранее лучше не оставлять функции с реализацией по умолчанию в виде "заглушки"

2023-07-21 17:42 UTC, RomkaGra4 commented on src/main/kotlin/lesson_18/lesson_18_task_3.kt
> +    open fun eat() = ""
"заглушки" - т.е. с пустым значением?)

2023-07-21 17:57 UTC, ievetrov commented on src/main/kotlin/lesson_18/lesson_18_task_3.kt
> +    open fun eat() = ""
ага) ну она просто возвращает пустую строку, хотя нигде не используется

2023-07-21 17:57 UTC, ievetrov approved these changes
отлично!

2023-07-21 17:58 UTC, merged