KS 18 - 5:  Completed task number 5 for lesson 18
RomkaGra4/KotlinSprint pull request #88
Opened 2023-07-21 16:21 UTC by RomkaGra4

2023-07-21 17:52 UTC, ievetrov requested changes
окей, а как сделать так, чтобы методы принимали еще и Float ?)

2023-07-21 17:57 UTC, RomkaGra4 commented
> окей, а как сделать так, чтобы методы принимали еще и Float ?)

Блин! Опять невнимательный я...))

2023-07-21 19:35 UTC, RomkaGra4 commented
Посмотри пожалуйста, так будет корректно? Я вроде разрешил указывать Float и/или Int. Но вместе с ними я получается в целом разрешил устанавливать любые типы данных...

2023-07-22 10:52 UTC, ievetrov commented
> Посмотри пожалуйста, так будет корректно? Я вроде разрешил указывать Float и/или Int. Но вместе с ними я получается в целом разрешил устанавливать любые типы данных...

не совсем так, лучше использовать принцип полиморфизма и сделать два метода. в одной сигнатуре Int, в другой Float

2023-07-22 10:53 UTC, ievetrov requested changes
добавить методы, которые принимают Float

2023-07-23 17:08 UTC, RomkaGra4 commented
Кажется, все верно... :)

2023-07-24 10:37 UTC, ievetrov approved these changes
все шикарно, ок)

2023-07-24 12:59 UTC, merged