KS 19 - 3: Completed task number 3 for lesson 19
RomkaGra4/KotlinSprint pull request #91
Opened 2023-08-15 07:14 UTC by RomkaGra4

2023-08-16 04:27 UTC, ievetrov requested changes

2023-08-16 04:27 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson_19_task_3.kt
> +enum class Spaceship(val id: Int){
а зачем тут `enum`? у нас же по условию один корабль, поэтому можно сделать класс с этими тремя методами)

2023-08-16 04:27 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson_19_task_3.kt
> +    //println(LANDING.getActionDescription())
комменты кода лучше не оставлять в продакшене)

2023-08-17 18:25 UTC, RomkaGra4 commented on src/main/kotlin/lesson_19/lesson_19_task_3.kt
> +enum class Spaceship(val id: Int){
Понял! Сглупил)

2023-08-17 18:25 UTC, RomkaGra4 commented on src/main/kotlin/lesson_19/lesson_19_task_3.kt
> +    //println(LANDING.getActionDescription())
Что значит "в продакшене"?)

2023-08-18 07:11 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson_19_task_3.kt
> +    //println(LANDING.getActionDescription())
код, который пишется в какой-либо компании для проекта)

2023-08-18 07:11 UTC, ievetrov approved these changes

2023-08-18 11:19 UTC, merged