KS 20 - 4: Completed task number 4 for lesson 20
RomkaGra4/KotlinSprint pull request #96
Opened 2023-08-26 16:29 UTC by RomkaGra4

2023-08-27 14:31 UTC, ievetrov requested changes

2023-08-27 14:31 UTC, ievetrov commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    val listOfElementsWithLambda = listOfElements.map {
А пробовал принудительно вывести тип переменной?) получается `List<Unit>`
У лямбды же иной тип. Также по ТЗ нужно именно запустить каждый четный элемент (не распечатать, а запустить метод печати) через () или invoke()

2023-08-27 17:34 UTC, RomkaGra4 commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    val listOfElementsWithLambda = listOfElements.map {
так... окей) Понял)

2023-08-28 10:54 UTC, ievetrov requested changes

2023-08-28 10:54 UTC, ievetrov commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    val listOfElementsWithLambda: (List<String>) -> List<Unit> = {
listOfElementsWithLambda у тебя сейчас стала функцией (не списком). Эта функция принимает список строк, но это не совсем то, что требуется все еще)

Инвокать нужно не весь список, а только четные элементы.

то есть:
1. сначала делаем из списка строк список лямбд
2. инвокаем нужные элементы в зависимости от четности индекса

здесь изначально есть ошибка в первом пункте. поэтому дальше логика нарушается. нужно добиться у списка лямбд такого типа `List<() -> Unit>`. То есть обычный список, но тип элементов лямбды.

```
    val listOfElementsWithLambda: List<() -> Unit> = listOfElements.map { // это фигурная скобка map
        { // это фигурная скобки инициализации лямбды для элемента
            println(it)
        }
    }
```

2023-08-28 17:13 UTC, RomkaGra4 commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    val listOfElementsWithLambda: (List<String>) -> List<Unit> = {
.. окей. Понял. Разбираюсь дальше))

2023-08-29 08:08 UTC, ievetrov requested changes

2023-08-29 08:08 UTC, ievetrov commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +        {
да) теперь каждый элемент списка хранит вот такое значение
 ```
       {
            println(it)
        }
```

в нем только надо прописать в принте "нажат элемент..." я не стал этого добавлять

2023-08-29 08:08 UTC, ievetrov commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    listOfElementsWithLambda.map {
а больше ничего мапить не нужно. дальше просто - пройтись циклом по списку, ну и вызывать то, что нужно по условию) и принт второй тоже лишний. все что нужно уже хранится в списке лямбд

2023-08-30 16:31 UTC, RomkaGra4 commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    listOfElementsWithLambda.map {
Перепроверил. Исправил) Долго думал и не понимал как вызвать список лямбд т.к. не находил инвок. А потом понял что ответ оказывается такой простой :))) Проверь пожалуйста, сейчас все корректно?)

2023-08-31 07:36 UTC, ievetrov requested changes

2023-08-31 07:36 UTC, ievetrov commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +            listOfElementsWithLambda[listOfElementsWithLambda.indexOf(it)].invoke()
а зачем тут так много наворочено, ведь `it` и есть искомый элемент, который надо запускать)

2023-09-01 10:49 UTC, ievetrov approved these changes
дожали) отлично

2023-09-01 14:08 UTC, merged