KS 11 - 5: Completed task number 5 for lesson 11
RomkaGra4/KotlinSprint pull request #97
Opened 2023-09-10 18:42 UTC by RomkaGra4

2023-09-11 11:33 UTC, ievetrov requested changes
будем допиливать)

2023-09-11 11:33 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +    val users = mutableListOf<String>()
Этот список будет типа User (внутри должны быть не просто строки, а объекты)

2023-09-11 11:33 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +    val messages = mutableListOf<String>()
этот типа Message соответственно

2023-09-11 11:33 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +    fun createNewMessage(message: String) {
в метод создания сообщения передавать id автора (то есть поле ранее созданного объекта пользователя)

2023-09-12 06:56 UTC, ievetrov requested changes
есть еще один пункт ТЗ

> id-шники новых объектов, а также подстановка авторов для сообщений реализована внутри класса Forum

2023-09-12 06:56 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +        messages.add(message)
передается authorId, но не используется)
давай по айдишнику искать автора среди списка юзеров и создавать объект мессадж (здесь).

2023-09-15 06:52 UTC, ievetrov requested changes
да, окей, но в объекте сообщения нужно хранить автора. иначе сообщение создается, а кто автор не совсем ясно

2023-09-16 11:28 UTC, ievetrov requested changes

2023-09-16 11:28 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +class UserForum(name: String, authorId: Int)
переменные без ключевого слова val. то есть не выделяется память под переменные. то есть передаешь значения и они попадают в никуда

2023-09-16 11:28 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +class UserForum(name: String, authorId: Int)
собственно поэтому не получается обратиться (не к чему просто)

2023-09-16 11:28 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +        val result = MessageForum(authorInMessage as UserForum,message.toString())
какого типа должна быть переменная authorInMessage ? укажи явно на 28 строке (для начала)

2023-09-16 12:06 UTC, RomkaGra4 commented
Кажется, получилось все как надо!) Не знаю конечно что ты скажешь по поводу самого кода... Можно ли его было как-то улучшить и сделать красивее, но на экран выводится та информация которая требовалась :)) Чему я очень сильно рад!)))

2023-09-16 20:36 UTC, ievetrov requested changes

2023-09-16 20:36 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +    forum.createNewUser(UserForum("КЛИЕНТ", 1))
итак, по ТЗ объект надо инкапсулировать. то есть создавать внутри метода. давай туда передавать только имя

2023-09-16 20:36 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +    forum.createNewUser(UserForum("КЛИЕНТ", 1))
а айдишник генерировать с помощью инкрементирующего счетчика

2023-09-16 20:36 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +            1 -> MessageForum(users[authorId - 1], message)
и вот тут ничего непонятно) два одинаковых ветвления. как то надо сделать более гибко, чтобы обрабатывать любое количество пользователей)

2023-09-18 12:52 UTC, ievetrov approved these changes
кажется все круто, победа!)

2023-09-18 16:05 UTC, merged