KS 12 - 5: Completed task number 5 for lesson 12
RomkaGra4/KotlinSprint pull request #98
Opened 2023-09-21 20:57 UTC by RomkaGra4

2023-09-22 07:38 UTC, ievetrov requested changes

2023-09-22 07:38 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +        Средняя температура днем:     ${averageDayTemperature / listOfDays.size}
Решение рабочее, однако, предлагаю решить более элегантным способом. А именно с использованием extension функции average(). То есть для списков каждого типа значений применяем эту функцию.

2023-09-22 07:38 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +    for (i in 1..10) {
логика верная, но теперь у нас есть ООП и можно создавать в одном цикле 10 объектов с нужными полями. и добавлять их в список

2023-09-23 08:41 UTC, ievetrov requested changes

2023-09-23 08:41 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +        listOfDays.add(DayAndNightWeather())
здесь у тебя создается 10 объектов с рандомными значениями сразу.

требуется отдельно проинициализировать список объектов в списке, например:    

```
for (i in 1..10) {
        listOfDays.add(
            DayAndNightWeather(
                dailyTemperature = listOfDays[i - 1].dailyTemperature,
                overnightTemperature = ...
            )
        )
    }
```

на основании списка объектов инициализируем списки со средним значением.

лучше разделить здесь логику, так код будет более понятным и удобным для доработок

2023-09-23 11:45 UTC, RomkaGra4 commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +        listOfDays.add(DayAndNightWeather())
Окей, понял. Разобрал. Проверь сейчас пожалуйста :)

2023-09-24 06:23 UTC, ievetrov requested changes

2023-09-24 06:23 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +                dailyTemperature = listOfDays[i - 1].dailyTemperature,
а в чем функциональный смысл брать значения из себя самого?

сейчас у тебя любой объект создается с рандомными значениями. это не совсем корректно, тк есть значения по умолчанию (некие базовые для всех), а рандомные вещи - это уже тестовые данные, которые приходит извне. в общем инициализировать поля класса предлагаю прям тут. а в объявлении класса уберем

2023-09-24 06:23 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +    val averageDayTemperature = listOf(DayAndNightWeather().dailyTemperature).average()
listOf(DayAndNightWeather().dailyTemperature) - тут вроде всего один элемент получается? и из него берется рандом. что-то не клеится

следует listOfDays обрабатывать, точнее доставать из него значения определенного типа и проходиться по всем дням

2023-10-11 16:40 UTC, ievetrov approved these changes
красота)

2023-10-17 18:14 UTC, merged