KS 19 - 5: Completed task number 5 for lesson 19
RomkaGra4/KotlinSprint pull request #99
Opened 2023-10-20 20:32 UTC by RomkaGra4

2023-10-21 07:23 UTC, ievetrov requested changes

2023-10-21 07:23 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson_19_task_5.kt
> +enum class Genders(val id: Int) {
все классы и структуры принято называть в единственном числе.

также можно немного упростить, передавая сюда не Int, а сразу текстовую запись для пола (мужчина/женщина), чтобы в дальнейшем можно было получить эту строку без дополнительных операций

2023-10-21 07:23 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson_19_task_5.kt
> +        else -> "пол не указан"
можно к `MALE` и `FEMALE` добавить также `UNDEFINED` или `ERROR`, тогда могли бы сразу знать что юзер ввел некорректные данные

2023-10-22 20:01 UTC, RomkaGra4 commented on src/main/kotlin/lesson_19/lesson_19_task_5.kt
> +enum class Genders(val id: Int) {
Готово. Посмотри, в том направлении пошел?)

2023-10-22 20:03 UTC, RomkaGra4 commented on src/main/kotlin/lesson_19/lesson_19_task_5.kt
> +        else -> "пол не указан"
Вань, вопрос - не совсем понимаю зачем добавлять UNDEFINED или ERROR если при введении "левой" информации нас все равно выкинет на else и там мы указываем что хотим. Посмотри пожалуйста код с корректировкой. Может такой вариант будет более лаконичным? Т.к. к примеру в class Human у меня не получается указать без else.

2023-10-23 14:11 UTC, ievetrov requested changes

2023-10-23 14:11 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson_19_task_5.kt
> +fun setGenders(gender: Gender): String {
к вопросу про `undefined` в Gender. сейчас внутри енама в поле textGender лежит по сути бесполезная информация, так как мы никак ее не используем и выводим данные все равно на русском языке) если положить туда вместо `MALE` `мужчина`, а вместо `FEMALE` `женщина`, то можно избавиться от этой функции `setGenders`

свойство `gender` из `Human` мы бы тогда могли сделать таким образом:
```
var gender = when (genderStr.lowercase()) {
        Gender.MALE.textGender -> Gender.MALE
        Gender.FEMALE.textGender -> Gender.FEMALE
        else -> Gender.UNDEFINED
    }
```

и тогда пользователь вводил бы пол по русски) получается небольшая оптимизация и выглядит логичнее

что касается `UNDEFINED` в енам, то это считается хорошей практикой, так как мы точно знаем что за объект должен к нам прийти на вход и как его нужно обрабатывать. это исключает возможные ошибки из-за невнимательности разработчика или неверных данных возвращаемых к примеру сервером)

2023-10-24 06:11 UTC, ievetrov approved these changes

2023-10-24 18:13 UTC, merged